apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appsets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nikita-akuity/tf-provider-example
    targetRevision: HEAD
    path: appset-manifests
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
